name: Playwright Tests Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run ESLint
    - name: Run ESLint
      run: npm run lint

    # Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install

    # Start the frontend server
    - name: Start Frontend Server
      run: npm start &
      env:
        CI: true  

    # Wait for frontend to be available on localhost:4200
    - name: Wait for Frontend
      run: |
        timeout 60s bash -c 'until echo > /dev/tcp/localhost/4200; do sleep 1; done'

    # Run Playwright tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Install Allure Commandline globally
    - name: Install Allure Commandline globally
      run: npm install -g allure-commandline

    # Generate Allure report
    - name: Generate Allure Report
      run: |
        allure generate ./allure-results -o ./allure-report --clean

    # Upload Allure report as an artifact
    - name: Upload Allure Report
      if: always()  
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: ./allure-report
