name: Playwright Tests Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      run: npm run lint

    # Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install

    # Install Allure Commandline globally
    - name: Install Allure Commandline globally
      run: npm install -g allure-commandline

    # Run Playwright tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Generate Allure report
    - name: Generate Allure Report
      run: |
        allure generate ./allure-results -o ./allure-report --clean

    # Upload Allure report as an artifact
    - name: Upload Allure Report
      if: always()  # Ensure this runs even if the tests fail
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: ./allure-report

  
